import { shield, allow } from 'graphql-shield'
import * as rules from './rules'

// Permissions

export const permissions = shield(
  {
    Query: {
      viewer: rules.isAuthenticated,
      user: allow,
      classroom: allow,
      class: allow,
      allClasses: allow,
      liveClasses: allow,
      upcomingClasses: allow,
      recordedClasses: allow,
    },
    Mutation: {
      createUser: rules.isAuthenticated,
      updateUser: rules.isAuthenticated,
      deleteUser: allow,
      follow: allow,
      unfollow: allow,
      createStripeAccount: allow,
      createStripeCustomer: allow,
      updateStripeCustomer: allow,
      createClassroom: allow,
      updateClassroom: allow,
      deleteClassroom: allow,
      joinClassroom: allow,
      leaveClassroom: allow,
      createClass: allow,
      updateClass: allow,
      deleteClass: allow,
      goLive: allow,
      createMessage: allow,
      createCharge: allow,
      createRefund: allow,
    },
    Viewer: {
      user: rules.isAuthenticated,
      requiresSetup: rules.isAuthenticated,
    },
    User: {
      id: allow,
      username: allow,
      email: allow,
      email_verified: allow,
      gender: allow,
      name: allow,
      description: allow,
      url: allow,
      picture: allow,
      video: allow,
      stripeId: allow,
      stripeCustomerId: allow,
      stripeURL: allow,
      defaultCard: allow,
      chargesConnection: allow,
      refundsConnection: allow,
      teachingClassroomsConnection: allow,
      studyingClassroomsConnection: allow,
      followersConnection: allow,
      followingConnection: allow,
    },
    DefaultCard: {
      last4: allow,
      expMonth: allow,
      expYear: allow,
      brand: allow,
    },
    Classroom: {
      id: allow,
      name: allow,
      description: allow,
      price: allow,
      classesConnection: allow,
      teacher: allow,
      studentsConnection: allow,
    },
    Class: {
      id: allow,
      name: allow,
      description: allow,
      price: allow,
      picture: allow,
      schedule: allow,
      live: allow,
      duration: allow,
      video: allow,
      files: allow,
      vod: allow,
      classroom: allow,
      messagesConnection: allow,
    },
    Message: {
      id: allow,
      createdAt: allow,
      text: allow,
      sender: allow,
    },
    Charge: {
      id: allow,
      createdAt: allow,
      amount: allow,
      class: allow,
      user: allow,
      refund: allow,
    },
    Refund: {
      id: allow,
      createdAt: allow,
      amount: allow,
      charge: allow,
    },
    File: {
      id: allow,
      name: allow,
      contentType: allow,
      url: allow,
    },
    Picture: {
      id: allow,
      name: allow,
      contentType: allow,
      url: allow,
    },
  },
  { debug: process.env.NODE_ENV !== 'production' },
)
